// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWmVo7iBYnJbdkyyG08Aso7R9n2AkxGeU',
    appId: '1:345554732477:web:56acc8b819e7c0e2107ed4',
    messagingSenderId: '345554732477',
    projectId: 'movie-app-fabce',
    authDomain: 'movie-app-fabce.firebaseapp.com',
    storageBucket: 'movie-app-fabce.firebasestorage.app',
    measurementId: 'G-85HEG2KJP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQn7-wrrSlkUNYa4h30NfZB5fIxgnzLMo',
    appId: '1:345554732477:android:88b70e7da7470c48107ed4',
    messagingSenderId: '345554732477',
    projectId: 'movie-app-fabce',
    storageBucket: 'movie-app-fabce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUk3D9a5_SuS-fjWRdf5Pmwm5fUyirJ6o',
    appId: '1:345554732477:ios:37fc2c12036e443e107ed4',
    messagingSenderId: '345554732477',
    projectId: 'movie-app-fabce',
    storageBucket: 'movie-app-fabce.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
